name: trainee_app
description: App de conexão entre alunos e profissionais (trainees) com mapa, chat, feed e mais.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase e autenticação
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.0
  google_sign_in: ^6.1.6

  # Mapa e localização
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0

  # Estado global
  provider: ^6.1.1

  # Upload de imagens
  image_picker: ^1.0.7

  # Utilitários
  flutter_local_notifications: ^17.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #assets:
   # - assets/images/ # (pasta onde ficarão ícones, avatares etc.)
