// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApIHV1aU6MFD86wB14trm1w2qw0D_QVI0',
    appId: '1:1048411156117:web:c3c9e2a262e98ee1c8f59c',
    messagingSenderId: '1048411156117',
    projectId: 'my-app-6d698',
    authDomain: 'my-app-6d698.firebaseapp.com',
    storageBucket: 'my-app-6d698.firebasestorage.app',
    measurementId: 'G-QW36ZFNMGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KaZT5a6m3YskRGa63DKgpLWW8wy4Sus',
    appId: '1:1048411156117:android:9e018d2c7de6df15c8f59c',
    messagingSenderId: '1048411156117',
    projectId: 'my-app-6d698',
    storageBucket: 'my-app-6d698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebPj8o5jR0hm_FPUZ9xgYeaF4zqJ5Q94',
    appId: '1:1048411156117:ios:d225d5a92ca09e2bc8f59c',
    messagingSenderId: '1048411156117',
    projectId: 'my-app-6d698',
    storageBucket: 'my-app-6d698.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebPj8o5jR0hm_FPUZ9xgYeaF4zqJ5Q94',
    appId: '1:1048411156117:ios:d225d5a92ca09e2bc8f59c',
    messagingSenderId: '1048411156117',
    projectId: 'my-app-6d698',
    storageBucket: 'my-app-6d698.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApIHV1aU6MFD86wB14trm1w2qw0D_QVI0',
    appId: '1:1048411156117:web:2ba430a0ecca9ef3c8f59c',
    messagingSenderId: '1048411156117',
    projectId: 'my-app-6d698',
    authDomain: 'my-app-6d698.firebaseapp.com',
    storageBucket: 'my-app-6d698.firebasestorage.app',
    measurementId: 'G-12Y74FJ8JS',
  );
}
